# Generated by Django 5.2.3 on 2025-10-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasensor',
            old_name='kelembapan',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='datasensor',
            old_name='suhu',
            new_name='temperature',
        ),
    ]
